Merging Feature branch into master Branch
guillainbisimwa/Bubble-sort pull request #1
Opened 2020-09-29 21:57 UTC by guillainbisimwa

- Implemented Bubble sort
- Implemented Bubble sort by
- Used Ruby

2020-09-29 23:56 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [x] How do I run this code if I wasn't familiar with programming ? That should be included in your readme.MD file
- [ ] What is bubble sort ? That should be included also
- [ ] For commits use imperative tense not past tense
- [ ] I noticed commits just from one person, Lets not repeat this in feature projects
- [ ] Check comments below
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-09-29 23:56 UTC, kobiyoyo commented on bubble_sort.rb
> +  print array
remove `print` because ruby returns the last statement automatically

2020-09-29 23:56 UTC, kobiyoyo commented on bubble_sort.rb
> +  print array
remove `print` because ruby returns the last statement automatically

2020-09-29 23:56 UTC, kobiyoyo commented on bubble_sort.rb
> +puts "\n"
Remove this debugging code

2020-09-29 23:56 UTC, kobiyoyo commented on bubble_sort.rb
> +bubble_sort([4, 3, 78, 2, 0, 2])
Remove this debugging code

2020-09-30 16:21 UTC, expjazz approved these changes
## Status: Project Approved :clap: 

Great work team :+1: 

You did all the changes and the algorithm is perfect.

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-09-30 16:29 UTC, merged